[2025-03-31T02:54:35.210+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag2.move_to_transformation scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T02:54:35.231+0100] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag2.move_to_transformation scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T02:54:35.232+0100] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-31T02:54:35.274+0100] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): move_to_transformation> on 2025-03-30 00:00:00+00:00
[2025-03-31T02:54:35.279+0100] {standard_task_runner.py:60} INFO - Started process 9862 to run task
[2025-03-31T02:54:35.290+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_dag2', 'move_to_transformation', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/complete.py', '--cfg-path', '/tmp/tmpebsh82xm']
[2025-03-31T02:54:35.293+0100] {standard_task_runner.py:88} INFO - Job 173: Subtask move_to_transformation
[2025-03-31T02:54:35.432+0100] {task_command.py:423} INFO - Running <TaskInstance: test_dag2.move_to_transformation scheduled__2025-03-30T00:00:00+00:00 [running]> on host LAPTOP-A4DHQTS9.
[2025-03-31T02:54:35.747+0100] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_dag2' AIRFLOW_CTX_TASK_ID='move_to_transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T02:54:35.792+0100] {base.py:83} INFO - Using connection ID 'destination_db' for task execution.
[2025-03-31T02:54:35.809+0100] {sql.py:450} INFO - Running statement: 
        INSERT INTO transformation.trans_prog3 
        SELECT * FROM staging.stg_prog3
        ON CONFLICT (uid) 
        DO UPDATE 
        SET lastupdated = EXCLUDED.lastupdated
        WHERE transformation.trans_prog3.lastupdated < EXCLUDED.lastupdated;
    , parameters: None
[2025-03-31T02:54:35.813+0100] {sql.py:459} INFO - Rows affected: 0
[2025-03-31T02:54:35.840+0100] {base.py:83} INFO - Using connection ID 'destination_db' for task execution.
[2025-03-31T02:54:35.859+0100] {sql.py:450} INFO - Running statement: 
        INSERT INTO transformation.trans_prog3
        SELECT * FROM staging.stg_prog3
        ON CONFLICT (uid) DO UPDATE 
        SET lastupdated = EXCLUDED.lastupdated
        WHERE transformation.trans_prog3.lastupdated < EXCLUDED.lastupdated;
    , parameters: None
[2025-03-31T02:54:35.863+0100] {sql.py:459} INFO - Rows affected: 0
[2025-03-31T02:54:35.867+0100] {python.py:201} INFO - Done. Returned value was: None
[2025-03-31T02:54:35.918+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_dag2, task_id=move_to_transformation, execution_date=20250330T000000, start_date=20250331T015435, end_date=20250331T015435
[2025-03-31T02:54:35.989+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-31T02:54:36.140+0100] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
